export default {
  sloganPart1: '우리동네 경매장',
  sloganPart2: '땅땅마켓',
  go: '시작하기',
  landing1: '좋은 물건을 구경하고 경매에 참여해보세요!',
  landing2: '실시간으로 원하는 물품을 검색해보세요!',
  landing3: '우리동네의 경매를 확인할 수 있어요!',
  landing4: '지금 바로 참여해보세요!',
  defaultLocation: '전국',
  searchPlaceHolder: '검색: 애플',
  goChat: '채팅',
  registeredItem: '등록한 경매',
  bidItem: '입찰한 경매',
  endBid: '입찰마감',
  noResult: '검색 결과가 없어요 :(',
  noResultDetail: '다른 검색어를 입력해보세요!',
  registerTitle: '경매 물품 등록',
  registerPlaceholder1: '제목을 입력해주세요',
  registerPlaceholder2: '최소 가격을 입력해주세요',
  registerPlaceholder3: '물품에 대한 설명을 입력해주세요',
  loginError: '로그인 후 이용해주세요.',
  registerInputError1: '모두 입력되어야 등록이 가능합니다.',
  registerInputError2: '설명은 100자 이내로 작성해야 합니다.',
  registerInputError3: '필수 입력사항입니다!',
  registerInputError4: '가격은 숫자만 입력 가능합니다!',
  registerInputError5: '가격은 1원 이상이어야 합니다!',
  registerInputError6: '금액 초과입니다!',
  registerInputError7: '사진을 등록해주세요!',
  registerInputError8: '경매 기간을 선택해주세요!',
  registerDay1: '1일',
  registerDay3: '3일',
  registerDay7: '7일',
  registerEndDay: '경매 마감일',
  noFilteredResult: '입찰/판매중인 물품이 없어요 :(',
  noFilteredResultDetail: '물건을 등록하거나 입찰해보세요!',
  buyerTitle: '입찰중인 상품',
  sellerTitle: '판매중인 상품',
  currentPrice: '현재가격: ',
  restTime: '남은시간: ',
  chatPlaceholder1: '메세지를 입력해주세요.',
  bidError: '이 경매는 더 이상 입찰할 수 없습니다.',
  nameUpdateTitle: '이름 변경',
  namePlaceholder: '변경할 이름을 입력해주세요.',
  nameInputError1: '닉네임은 1글자 이상, 12글자 이하여야 합니다.',
  nameInputError2: '공백, 특수문자는 사용할 수 없습니다.',
  btnChange: '변경',
  mobileRegisterMenu: '경매등록',
  mobileSellerMenu: '판매상품',
  mobileBuyerMenu: '입찰상품',
  filterBuyer: '입찰',
  filterSeller: '판매',
  locationError: '위치가 없어요!',
};